[package]
name = "axum-handler-example"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.4", features = ["macros"] }
sqlx = { version = "0.8.5", features = ["postgres"] }
tokio = { version = "1.45.0", features = ["full", "macros"] }
